# Generated by Django 4.2.10 on 2024-03-03 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("surname", models.CharField(max_length=128, verbose_name="Surname")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Patronymic"
                    ),
                ),
            ],
            options={"verbose_name": "Автор", "verbose_name_plural": "Авторы",},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, verbose_name="Product Name"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Product start date")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Product price"
                    ),
                ),
                (
                    "min_students",
                    models.IntegerField(
                        default=10,
                        verbose_name="Minimum numbers of students in a group",
                    ),
                ),
                (
                    "max_students",
                    models.IntegerField(
                        default=30,
                        verbose_name="Maximum numbers of students in a group",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_api.author",
                        verbose_name="author",
                    ),
                ),
            ],
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("surname", models.CharField(max_length=128, verbose_name="Surname")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Patronymic"
                    ),
                ),
            ],
            options={"verbose_name": "Студент", "verbose_name_plural": "Студенты",},
        ),
        migrations.CreateModel(
            name="ProductAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access", models.BooleanField(default=True, verbose_name="Access")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_api.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_api.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={"verbose_name": "Доступ к продукту",},
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Lesson name")),
                ("video", models.URLField(max_length=256)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_api.product",
                        verbose_name="product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Group name")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_api.product",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        to="school_api.student", verbose_name="list of students"
                    ),
                ),
            ],
        ),
    ]
